[icons]
icons = "material-nf"

[theme]
theme = "ctp-mocha"

[[block]]
block = "sound"
max_vol = 100
step_width = 2
format = " $icon { $volume |} {$active_port |}" 

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid} "

[[block]]
block = "time"
interval = 60
format = " $icon {$timestamp.datetime(f:'%R')} "

